global:
  mariadb:
    nameOverride: eric-oss-mariadb
  registry:
    url: armdocker.rnd.ericsson.se
  hosts:
    iam: "iam.ericsson.com"
  iam:
    clientId: "eo"
    adminSecret: eric-sec-access-mgmt-creds
    userKey: kcadminid
    passwordKey: kcpasswd
    cacert:
      secretName: iam-cacert-secret
      key: tls.crt
      filePath: iam/ca.crt

imageCredentials:
  # repoPath include the image path relative to the registry url, excluding image name
  policyXACMLImage:
    repoPath: # see default in eric-product-info.yaml
    registry:
      imagePullPolicy: IfNotPresent
  keycloakImage:
    repoPath: # see default in eric-product-info.yaml
    registry:
      imagePullPolicy: IfNotPresent

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%

debug: false
replicas: 1
port:
  http: 6969
  https: 443
  jvmDebug: 9001
  jvmJmxRemote: 9002

service:
  port:
    http: 6969
    https: 443
  type: ClusterIP
  name: policy-xacml-pdp
  portName: policy-xacml-pdp
  externalPort: 6969
  internalPort: 6969
jvmOptions:
- "-XX:+UnlockExperimentalVMOptions"
- "-XX:+UseCGroupMemoryLimitForHeap"
- "-XX:+UseG1GC"
- "-Xms100m"
- "-Xmx2048m"
jvmDebugOptions:
- "-agentlib:jdwp=transport=dt_socket,server=y,address=9001,suspend=n"
- "-Dcom.sun.management.jmxremote"
- "-Dcom.sun.management.jmxremote.ssl=false"
- "-Dcom.sun.management.jmxremote.authenticate=false"
- "-Dcom.sun.management.jmxremote.local.only=false"
- "-Djava.rmi.server.hostname=127.0.0.1"
- "-Dcom.sun.management.jmxremote.port=9002"
- "-Dcom.sun.management.jmxremote.rmi.port=9002"

resources:
  xacml:
    requests:
      memory: "350M"
      cpu: 1000m
      ephemeral-storage:
    limits:
      memory: "500M"
      cpu: 1000m
      ephemeral-storage:
  keycloak:
    requests:
      memory: 1Gi
      cpu: 100m
      ephemeral-storage:
    limits:
      memory: 3Gi
      cpu: 1000m
      ephemeral-storage:

logging:
  format:
    json: false

liveness:
  initialDelaySeconds: 120
  periodSeconds: 10
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: true

readiness:
  initialDelaySeconds: 120
  periodSeconds: 10

labels: {}
terminationGracePeriodSeconds: 30

podPriority:
  eric-oss-pf-xacml:
    priorityClassName: