apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-oss-pf-xacml-configmap.name" . }}
  labels:
    app: {{ template "eric-oss-pf-xacml-configmap.name" . }}
  {{- include "eric-oss-pf-xacml.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-pf-xacml.eric-product-info" .| nindent 4 }}
data: 
{{ tpl (.Files.Glob "resources/config/*.json").AsConfig . | indent 2 }}